name: remove

on:
  workflow_dispatch:
    inputs:
      package:
        description: Which package to remove
        required: true

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        include: [
          { msystem: mingw32, toolchain: i686 },
          { msystem: mingw64, toolchain: x86_64 },
          { msystem: ucrt64, toolchain: ucrt-x86_64 }
        ]
      fail-fast: false
    defaults:
      run:
        shell: msys2 {0}
    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: msys2/setup-msys2@v2
        with:
          msystem: MSYS
          install: git
          update: true

      - name: Fetch and update index
        run: ./ci-remove.sh
        env:
          MINGW_ARCH: ${{ matrix.msystem }}
          MINGW_TOOLCHAIN: ${{ matrix.toolchain }}
          PACMAN_REPOSITORY: ${{ matrix.msystem }}
          PACKAGE: ${{ github.event.inputs.package }}

      - name: "Save new package index"
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.msystem }}
          path: artifacts/

  deploy:
    name: Deploy to staging server
    runs-on: ubuntu-20.04
    needs: [build]
    if: success() && github.ref == 'refs/heads/master'
    steps:
      - name: Get artifacts for deployment
        uses: actions/download-artifact@v2
      - id: deployment
        name: Uploading files
        run: |
          ls -ltrR
          mkdir -p ~/.ssh
          echo "StrictHostKeyChecking no" > ~/.ssh/config
          echo "${STAGINGKEY}" > ~/.ssh/id_rsa && chmod 400 ~/.ssh/id_rsa
          echo 'put -pr .' | sftp "${STAGINGUSER}@ftp.opencpu.org:/rtools"
          rm -f ~/.ssh/id_rsa
        env:
          STAGINGUSER: ${{ secrets.STAGINGUSER }}
          STAGINGKEY: ${{ secrets.STAGINGKEY }}
